[MIG][10.0] account_analytic_distribution module
OCA/account-analytic pull request #100
Opened 2017-05-22 15:14 UTC by cubells

- Minor changes from version 9.0

cc @Tecnativa

2017-05-24 23:40 UTC, pedrobaeza requested changes
Little changes, but overall OK

2017-05-24 23:40 UTC, pedrobaeza commented on account_analytic_distribution/__manifest__.py
> +    "website": "http://www.tecnativa.com",
https

2017-05-24 23:40 UTC, pedrobaeza commented on account_analytic_distribution/__manifest__.py
> +        "account",
Also on analytic?

2017-05-24 23:40 UTC, pedrobaeza commented on account_analytic_distribution/migrations/9.0.1.0.0/pre-migration.py
> +# -*- coding: utf-8 -*-
Remove this file

2017-05-25 07:55 UTC, pedrobaeza commented
Please fix this, @cubells 

@chienandalu @luismontalba please review

2017-05-25 08:00 UTC, cubells commented on account_analytic_distribution/__manifest__.py
> +        "account",
account module already has analytic dependency. It's not necessary.

2017-05-25 16:22 UTC, pedrobaeza approved these changes

2017-05-25 18:48 UTC, chienandalu approved these changes
Tested on runbot :+1:

2017-05-25 19:17 UTC, luismontalba reviewed
Testing PR on runbot I can mark the check for "Force percent" even logged with admin, having adviser rights and developer mode active. Is it an issue?

2017-05-25 19:21 UTC, pedrobaeza commented
Are you on edit mode?

2017-05-26 07:05 UTC, cubells commented
@luismontalba can you retest now?

2017-05-26 08:21 UTC, luismontalba commented
I can mark the "Force percent" check now, but then I can create a distribution with two lines 75% and 24% ,and I think this check should avoid it. Isn't it?
I can't see the analytic account entries menu in adviser menu (with related permission activated)

2017-05-26 08:33 UTC, cubells commented
@luismontalba 

yes, you are right. I'm working on it.

2017-06-06 08:43 UTC, cubells commented
@luismontalba @chienandalu 

Can you retest?

2017-06-06 09:12 UTC, cubells commented
runbot error is due to analytic_tag_dimension module.

2017-06-08 14:18 UTC, luismontalba commented
The think is now I can't see the "Force percent" check ... can you?

2017-06-08 16:40 UTC, pedrobaeza commented
Rebasing now should be green

2017-06-08 16:42 UTC, cubells commented
@luismontalba force percent field is in company form. Now you can force percent by company.

2017-06-08 17:33 UTC, cubells commented
@pedrobaeza 
It's green.

2017-06-08 17:34 UTC, pedrobaeza commented
@luismontalba please give your final blessing.

2017-06-08 17:44 UTC, luismontalba approved these changes
The "Force percent" check works fine

2017-06-08 17:49 UTC, merged