[10.0][MIG] account_asset_analytic
OCA/account-analytic pull request #102
Opened 2017-05-24 09:36 UTC by luismontalba

Account asset analytic
==================
This module allows you to define an analytic account per asset and creates
expenses moves with that analytic account instead of the analytic account
per category, as the standard does.
It also propagates analytic account from invoice line to analytic account line.

cc @Tecnativa

2017-05-24 23:34 UTC, pedrobaeza approved these changes
Little changes, but overall OK

2017-05-24 23:34 UTC, pedrobaeza commented on account_asset_analytic/__init__.py
> +# © 2016 Antonio Espinosa - <antonio.espinosa@tecnativa.com>
You can remove copyright from init files.

2017-05-24 23:34 UTC, pedrobaeza commented on account_asset_analytic/__manifest__.py
> +# © 2016 Antonio Espinosa - <antonio.espinosa@tecnativa.com>
Replace `©` by `Copyright` and add yours

2017-05-24 23:34 UTC, pedrobaeza commented on account_asset_analytic/__manifest__.py
> +    "website": "http://www.tecnativa.com",
https

2017-05-24 23:34 UTC, pedrobaeza commented on account_asset_analytic/__manifest__.py
> +        "account_asset",
Doesn't it depend on `analytic`?

2017-05-24 23:34 UTC, pedrobaeza commented on account_asset_analytic/models/__init__.py
> +# © 2016 Antonio Espinosa - <antonio.espinosa@tecnativa.com>
Remove copyright here

2017-05-25 09:13 UTC, luismontalba commented on account_asset_analytic/__manifest__.py
> +        "account_asset",
Yes, but throw this route:
account_asset > account_accountant > Account > analytic

2017-05-25 12:04 UTC, pedrobaeza requested changes
The drop in coverage means that there are certain things untested. See here what it's untested and check, because I think that the analytic account propagation to the asset is not correct:

https://codecov.io/gh/OCA/account-analytic/compare/8e5514369405d8bb2980c65add9b41a1666d0f43...4f61bdaf9d6969b32b0edda3380efadde02af1b6/diff

2017-05-25 18:06 UTC, luismontalba commented
Runbot can't build due to other modules test

2017-05-25 18:09 UTC, pedrobaeza commented
Runbot is building, but it fails with a warning. Anyway, it's possible to test the module in runbot.

2017-05-25 20:05 UTC, pedrobaeza commented
@cubells can you review?

2017-05-26 05:51 UTC, cubells approved these changes
:+1: 

Code review and tested

2017-06-09 01:33 UTC, pedrobaeza approved these changes

2017-06-09 01:33 UTC, merged