[10.0] analytic_tag_dimension: fix/improve README
OCA/account-analytic pull request #139
Opened 2017-11-17 15:19 UTC by alexis-via

2017-11-17 15:44 UTC, LoisRForgeFlow approved these changes

2017-11-17 15:47 UTC, pedrobaeza requested changes

2017-11-17 15:47 UTC, pedrobaeza commented on analytic_tag_dimension/README.rst
> +* Analytic Entries with Tags created before installation this module are not updated with its Dimensions.
s/installation/installing

2017-11-17 15:47 UTC, pedrobaeza commented on analytic_tag_dimension/README.rst
> +* On function that create fields, get all models that inherit from AbstractModel
s/On function/On the function
s/get all model/get all the models

2017-11-18 12:27 UTC, pedrobaeza approved these changes

2017-11-18 12:28 UTC, merged