[WIP] 11.0 mig analytic tag dimension sale warning
OCA/account-analytic pull request #148
Opened 2018-01-05 11:19 UTC by mpanarin

2018-01-08 08:52 UTC, simahawk approved these changes

2018-01-08 08:53 UTC, simahawk commented
@mpanarin remove `[WIP]` if not needed

2018-01-17 13:42 UTC, ghost requested changes

2018-01-17 13:42 UTC, arkostyuk commented on analytic_tag_dimension_sale_warning/__manifest__.py
> +        'sale'
Trailing comma please

2018-01-22 11:51 UTC, melroy89 approved these changes

2018-01-23 08:41 UTC, ghost approved these changes

2018-01-25 07:41 UTC, simahawk commented
REMINDER: depends on https://github.com/OCA/account-analytic/pull/146 => update oca_dependencies.txt before merge

2018-01-31 08:39 UTC, grindtildeath reviewed
oca_dependencies to update, otherwise LGTM ! 👍

2018-01-31 08:39 UTC, grindtildeath commented on oca_dependencies.txt
> +account-analytic https://github.com/arkostyuk/account-analytic 11.0-mig-analytic_tag_dimension
As #146 is merged, you can remove this line.

2018-01-31 09:44 UTC, yvaucher approved these changes

2018-01-31 09:44 UTC, merged