11.0 mig analytic department
OCA/account-analytic pull request #167
Opened 2018-04-04 16:25 UTC by Tonow-c2c

2018-04-05 02:13 UTC, elicoidal requested changes
mostly details.
LGTM

2018-04-05 02:13 UTC, elicoidal commented on analytic_department/LICENSE
> +OpenERP, Open Source Management Solution
remove this and merge the relevant content in README

2018-04-05 02:13 UTC, elicoidal commented on analytic_department/README.rst
> +.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
svg ->png

2018-04-05 02:13 UTC, elicoidal commented on analytic_department/README.rst
> +   :target: https://runbot.odoo-community.org/runbot/87/9.0
update branch

2018-04-05 02:13 UTC, elicoidal commented on analytic_department/__manifest__.py
> +    "website": "http://camptocamp.com",
target repo URL

2018-04-05 02:13 UTC, elicoidal commented on analytic_department/i18n/analytic_department.pot
> +# Translation of OpenERP Server.
remove this file

2018-04-05 02:13 UTC, elicoidal commented on analytic_department/views/analytic.xml
> +        <filter string="Department" icon="terp-folder-orange" domain="[]" context="{'group_by':'department_id'}"/>
improve the format for readibility

2018-04-05 05:04 UTC, feketemihai commented
@Tonow-c2c @elicoidal I don't see the reason of having a new module just to add some views that should be in the dependant module, so i suggest to improve analytic_base_department, because there we add the fields.

2018-04-05 07:10 UTC, elicoidal commented
@feketemihai what you suggest makes sense actually!

2018-04-05 13:05 UTC, damdam-s commented
@feketemihai @elicoidal we did this way because this module exists in v9 so we migrated this one. 

BTW, if other people agree, no problems to improve the `analytic_base_department` module.

@gurneyalex @pedrobaeza any opinion?

2018-04-05 13:29 UTC, pedrobaeza commented
Yes, I see the merge reasonable if you don't mind.

2018-04-10 05:11 UTC, feketemihai commented
@Tonow-c2c Can you please squash last 2 commits, otherwise :+1:

2018-04-11 12:18 UTC, Tonow-c2c commented
@elicoidal it seems better to you ?

2018-04-12 01:21 UTC, elicoidal requested changes

2018-04-12 01:21 UTC, elicoidal commented on analytic_base_department/__manifest__.py
> +    "depends": ["account",
Are you sure you need to explicit the dependency?

2018-04-12 01:21 UTC, elicoidal commented on analytic_base_department/views/analytic.xml
> +        <filter string="Department" icon="terp-folder-orange" domain="[]" context="{'group_by':'department_id'}"/>
Could you improve the formating for readability?
Are you sure the icon is available in newest Odoo versions?
(a `grep terp-folder-orange . -r` in standard v11 returns nothing)

2018-04-12 10:31 UTC, damdam-s commented on analytic_base_department/__manifest__.py
> +    "depends": ["account",
@elicoidal I think explicit is better than implicit :smile: 

Of course not needed but it doesn't bother IMHO

2018-04-17 13:36 UTC, damdam-s commented on analytic_base_department/__manifest__.py
> +    "depends": ["account",
@elicoidal you really want @Tonow-c2c to delete the explicit dependency or we can go with it?

2018-04-17 14:09 UTC, elicoidal commented on analytic_base_department/__manifest__.py
> +    "depends": ["account",
not blocking for me @damdam-s @Tonow-c2c

2018-04-18 06:31 UTC, damdam-s commented
@feketemihai @pedrobaeza can you please review and eventually approve :smile: ?
@elicoidal thanks for not blocking this one. Can you please "dismiss" your review or make another one in order to remove "red and requested changes"?

Have a nice day

2018-04-18 06:59 UTC, elicoidal approved these changes
(no functional tests)

2018-04-18 08:52 UTC, feketemihai commented
@damdam-s I will still need the squash of last commits...

2018-04-23 09:13 UTC, Tonow-c2c commented
@feketemihai squash done :wink:

2018-04-26 14:29 UTC, tschanzt approved these changes
Tested. works and no issue with the changes.

2018-05-03 13:11 UTC, p-tombez approved these changes
LGTM, code review only

2018-05-03 13:31 UTC, damdam-s approved these changes
thanks

2018-05-04 07:48 UTC, simahawk requested changes

2018-05-04 07:48 UTC, simahawk commented on analytic_base_department/README.rst
update whole readme according to https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst

2018-05-18 07:32 UTC, feketemihai commented
@Tonow-c2c can you squash last commits, and i think this should be merged...

@pedrobaeza

2018-05-18 07:40 UTC, Tonow-c2c commented
@feketemihai Commit squashed :wink:

2018-05-18 07:46 UTC, simahawk approved these changes

2018-05-18 14:56 UTC, merged