[10.0][IMP] account_analytic_parent: propagate active through hierarchy
OCA/account-analytic pull request #196
Opened 2018-10-19 12:11 UTC by mreficent

Fix of https://github.com/OCA/account-analytic/pull/193.

@aheficent could you test it, please?

2018-10-29 12:56 UTC, AaronHForgeFlow approved these changes
:+1: Functional tests. Thanks.

2018-10-30 09:06 UTC, LoisRForgeFlow approved these changes
LGTM :+1:

2018-11-16 13:40 UTC, mreficent commented
@pedrobaeza

2018-11-16 14:51 UTC, pedrobaeza requested changes
This doesn't propagate active to grandson and so

2018-11-16 14:51 UTC, pedrobaeza commented on account_analytic_parent/models/account_analytic_account.py
> +            self.mapped('child_ids').archive_account()
```suggestion
            self.mapped('child_ids').write({'active': False})
```
and remove extra method

2018-11-16 16:30 UTC, mreficent commented
It propagates, because when you do `self.mapped('child_ids').write()`, then it will enter again in the `write` but for their children and thus will execute a `self.mapped('child_ids').write()` for the grandson and so on.

2018-11-16 16:32 UTC, pedrobaeza commented
Right, thanks for the note.

2018-11-16 17:31 UTC, mreficent commented
ready :green_apple:

2018-11-16 17:33 UTC, merged