[FIX] Moved merging check from purchase order level to line level.
OCA/account-analytic pull request #217
Opened 2019-01-15 12:40 UTC by n17

- Link to Avoin Systems pull request: https://github.com/avoinsystems/account-analytic/pull/1

2019-01-15 12:48 UTC, n17 commented
I have indeed signed the CLA.

2019-01-23 11:46 UTC, aisopuro commented
@pedrobaeza I understand there was at some point some kind of bug with the CLA-bot which caused it to complain about signing the CLA even though it had been signed. Has that issue been fixed? We're pretty sure that @n17 has signed the CLA.

2019-01-23 13:34 UTC, pedrobaeza commented
Well, the check was probably done before we inserted the CLA tag in the proper contact (which is handled manually), so don't worry too much about that now. If you do another PR and the message appears again, then please report back.

2019-02-07 11:45 UTC, aisopuro commented
This one is still looking for reviewers. Would @jbeficent know if anyone is able?

2019-02-07 16:40 UTC, Nikul-Chaudhary reviewed
Improve Code

2019-02-07 16:40 UTC, Nikul-Chaudhary commented on procurement_mto_analytic/models/purchase_order_line.py
> +        if len(self.account_analytic_id) == 0:
@n17 Use like this `if not self.account_analytic_id:`, not checked len of account

2019-02-07 16:40 UTC, Nikul-Chaudhary commented on procurement_mto_analytic/tests/test_purchase_procurement_analytic.py
> +        cls.analytic_account_2 = cls.env['account.analytic.account'].create({
` cls.env['account.analytic.account']` Use multiple time, so use like global

2019-02-07 16:40 UTC, Nikul-Chaudhary commented on procurement_mto_analytic/tests/test_purchase_procurement_analytic.py
> +        self.env['sale.order.line'].create({
same as `self.env['sale.order.line']`

2019-02-08 11:28 UTC, n17 commented
@Nikul-Chaudhary Is this what you had in mind?

2019-02-19 14:06 UTC, aisopuro commented
@Nikul-Chaudhary is this ready to merge now or is something still needed?

2019-02-25 16:29 UTC, Nikul-Chaudhary approved these changes
Code Review LGTM :+1:

2019-02-26 07:06 UTC, aisopuro commented
Thanks @Nikul-Chaudhary . Do you know anyone who would be able to do the second review and merge if OK?

2019-02-26 16:23 UTC, Nikul-Chaudhary commented
@pedrobaeza please take a look?

2019-02-26 16:24 UTC, pedrobaeza commented
Please explain the purpose of the PR

2019-02-26 16:34 UTC, Nikul-Chaudhary commented
> Please explain the purpose of the PR

can you please @n17 n17 @aisopuro

2019-02-28 08:05 UTC, n17 commented
@pedrobaeza
This PR changes the logic by which `procurement_mto_analytic` decides if new lines should be merged into existing purchase orders. The original ported functionality did not merge order lines to the same purchase if they had different analytic accounts, even if they were otherwise compatible (same supplier etc). This code changes the functionality so that the different lines are added to the same purchase order, even though they stay separate on the purchase order. This way the module can make use of procurement settings that allow procured amounts to be collected onto larger purchase orders, instead of always forcing them to be split into many smaller orders.

2019-02-28 08:14 UTC, pedrobaeza requested changes
Remove all extra blank lines inside methods.

Add yourself to contributors in the module and put your copyright in the new file

2019-02-28 08:14 UTC, pedrobaeza commented on procurement_mto_analytic/models/purchase_order_line.py
> +        if values.get('account_analytic_id') != po_line_analytic_account:
Do directly: `if values.get('account_analytic_id') != self.account_analytic_id.id:`, remove previous `if`

2019-02-28 08:14 UTC, pedrobaeza commented on procurement_mto_analytic/models/purchase_order_line.py
> +        # Do not merge into a line with a different analytic account
Do it a docstring (with `"""`)

2019-02-28 08:14 UTC, pedrobaeza commented on procurement_mto_analytic/models/purchase_order_line.py
> +
Remove blank lines inside a method. It's a waste of space and doesn't add anything valuable.

2019-02-28 08:14 UTC, pedrobaeza commented on procurement_mto_analytic/tests/test_purchase_procurement_analytic.py
> +
Remove empty lines inside a method

2019-02-28 14:06 UTC, n17 commented
@pedrobaeza I made the requested changes but the lint check fails with a strange error. Could you please take a look?

2019-02-28 14:09 UTC, pedrobaeza commented
The lint error is due to https://github.com/OCA/maintainer-quality-tools/issues/589. Working on fixing it.

2019-02-28 14:58 UTC, pedrobaeza approved these changes

2019-02-28 14:58 UTC, merged