12.0 mig analytic tag dimension
OCA/account-analytic pull request #234
Opened 2019-04-29 13:45 UTC by jaumeplanas

2019-04-29 13:53 UTC, pedrobaeza commented
Please squash together adjacent "OCA Transbot.." commits using https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests

2019-04-30 08:13 UTC, jaumeplanas commented
Any idea why Runbot is failing?

2019-04-30 08:16 UTC, pedrobaeza commented
It's due to 2 warnings:
```
2019-04-30 07:36:45,285 167 WARNING openerp_test odoo.models: The model account.analytic.dimension has no _description
2019-04-30 07:36:45,286 167 WARNING openerp_test odoo.models: The model analytic.dimension.line has no _description
```

2019-04-30 08:16 UTC, jaumeplanas commented
Thanks

2019-04-30 10:05 UTC, jaumeplanas commented
All green, when merged I'll migrate the other two dependent addons

2019-06-17 11:17 UTC, Tardo requested changes

2019-06-17 11:17 UTC, Tardo commented on analytic_tag_dimension/readme/CONFIGURE.rst
> +* go to /Accounting/Configuration/Analytic Accounting/Analytic Accounts Dimensions to create new Analytic Dimensions.
Update these information with the correct way to configure this module

2019-06-17 11:17 UTC, Tardo commented on analytic_tag_dimension/readme/USAGE.rst
> +.. image:: https://odoo-community.org/website/image/ir.attachment/5784_f2813bd/datas
Remove this file if not really used. gen-readme script will write runbot button.

2019-06-17 12:04 UTC, jaumeplanas commented on analytic_tag_dimension/readme/USAGE.rst
> +.. image:: https://odoo-community.org/website/image/ir.attachment/5784_f2813bd/datas
Removed

2019-06-19 15:52 UTC, Tardo approved these changes
LGTM, code review. Thanks :+1:

2019-06-26 11:55 UTC, pedrobaeza commented
@jaumeplanas please NEVER resolve conflicts with a merge operation. It has been a nightmare to solve the conflicts when plaining the commit history. About the migration itself, note that on new README by fragments, you shouldn't put the title in DESCRIPTION.rst file. I have already amended this.

So let's merge this after both operations have been done.

2019-06-26 11:55 UTC, pedrobaeza commented
/ocabot merge

2019-06-26 14:54 UTC, merged