13.0 mig account analytic required
OCA/account-analytic pull request #255
Opened 2019-10-01 09:17 UTC by jimhoefnagels

2019-10-01 14:09 UTC, schout-it approved these changes
lgtm

2019-11-21 13:01 UTC, CasVissers-360ERP approved these changes
LGTM!

2020-01-27 09:09 UTC, jimhoefnagels commented
Could this PR be merged please?
thanks

2020-02-03 10:33 UTC, ivantodorovich requested changes

2020-02-03 10:33 UTC, ivantodorovich commented on oca_dependencies.txt
> +account-financial-tools https://github.com/rven/account-financial-tools 13.0-mig-account_menu
```suggestion
account-financial-tools
```

If this PR depends on another, we should wait for the other to be merged first.
In this case I think it's already merged.

You can remove the comments on this file aswell

2020-02-06 15:37 UTC, ivantodorovich approved these changes
LGTM!

I would ask you to: 

> Squash administrative commits (if any) with the previous commit for reducing commit noise. They are named as "[UPD] README.rst", "[UPD] Update $MODULE.pot", "Update translation files" and similar names, and comes from OCA-git-bot, oca-travis or oca-transbot.

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-13.0

Otherwise :+1:

2020-02-12 12:15 UTC, jimhoefnagels commented
Hi @pedrobaeza 
Can this PR be merged? Thanks

2020-02-12 12:16 UTC, pedrobaeza commented
Sorry, I'm no more OCA's community manager for handling these things. Any way, let's do it for one more time:

/ocabot merge

2020-02-12 12:29 UTC, sbidoul commented
> Sorry, I'm no more OCA's community manager for handling these things. Any way, let's do it for one more time

Note that strictly speaking, merging a PR is the responsibility of the addon maintainer or [PSC members](https://odoo-community.org/psc-teams/accounting-9). So this case the right group to ping is @OCA/accounting-maintainers.

2020-02-12 12:37 UTC, merged