[14.0][MIG] account_analytic_default_purchase: Migration to 14.0
OCA/account-analytic pull request #365
Opened 2021-03-09 15:00 UTC by Reyes4711

Standard migration to 14.0

2021-03-11 17:36 UTC, ferran-73 commented
A second commit has been added updating the dependencies due to the test needing purchase_stock module to run.

2022-02-14 21:30 UTC, carlosdauden requested changes
Can you take a look at this PR or take it as a base to do the migration?
https://github.com/OCA/account-analytic/pull/438

2022-02-14 21:30 UTC, carlosdauden commented on account_analytic_default_purchase/models/purchase.py
> +            self.env.uid,
At this position the param is account_id instead of user_id:
https://github.com/odoo/odoo/blob/3e598a8014966e1a07a08d53bf85050b458e05a6/addons/account/models/account_analytic_default.py#L31
Use param names to avoid this error.

2022-02-14 21:30 UTC, carlosdauden commented on account_analytic_default_purchase/models/purchase.py
> +                self.account_analytic_id = rec.analytic_account_id.id
Does `analytic_account_id` field exist in the model?:
https://github.com/odoo/odoo/blob/3e598a8014966e1a07a08d53bf85050b458e05a6/addons/account/models/account_analytic_default.py#L15

2022-02-15 10:38 UTC, carlosdauden commented
Please close this PR.
This module is not needed in v14:
https://github.com/odoo/odoo/blob/9e48afe5bf4f52b7cc2705fe434b4647df752a59/addons/purchase/models/purchase.py#L993-L1017

2022-02-15 12:48 UTC, closed without merging