[MIG] purchase_analytic: Migration to 16.0
OCA/account-analytic pull request #524
Opened 2023-01-16 05:25 UTC by AungKoKoLin1997

@qrtl

2023-01-17 17:36 UTC, RodrigoBM approved these changes
LGFM!

2023-01-18 15:35 UTC, yostashiro requested changes

2023-01-18 15:35 UTC, yostashiro commented on purchase_analytic/models/purchase.py
> +    )
```suggestion
    _name = "purchase.order"
    _inherit = ["purchase.order", "analytic.mixin"]

    analytic_distribution = fields.Json(
        inverse="_inverse_analytic_distribution",
        readonly=True,
        states={"draft": [("readonly", False)]},
    )
```

2023-01-18 15:35 UTC, yostashiro commented on purchase_analytic/views/purchase_views.xml
> +                    options="{'product_field': 'product_id', 'business_domain': 'purchase_order'}"
```suggestion
```
I think these options are of no use here.

2023-01-19 02:28 UTC, yostashiro approved these changes
LGTM. 👍

@AungKoKoLin1997 Please squash your migration commits.

2023-01-21 20:51 UTC, AaronHForgeFlow approved these changes
Functional LG

2023-01-22 03:28 UTC, yostashiro reviewed
@AungKoKoLin1997 Can you please also add the analytic_distribution field in the RFQ tree view (purchase.purchase_order_kpis_tree) in the same manner as in the purchase order tree view.

2023-01-22 03:28 UTC, yostashiro commented on purchase_analytic/views/purchase_views.xml
> +                />
```suggestion
                <field
                    name="analytic_distribution"
                    widget="analytic_distribution"
                    groups="analytic.group_analytic_accounting"
                    optional="show"
                />
```
Got feedback from a user that they want to be able to hide the column.

2023-01-22 08:24 UTC, yostashiro commented
@AungKoKoLin1997 Thanks! LGTM.

2023-02-02 07:17 UTC, yostashiro commented on purchase_analytic/models/purchase.py
> +        states={"draft": [("readonly", False)]},
```suggestion
        # To be consistent with order_line readonly behavior
        states={"done": [("readonly", True)], "cancel": [("readonly", True)]},
```
@AungKoKoLin1997

2023-02-02 09:40 UTC, yostashiro approved these changes
👍

2023-02-04 23:19 UTC, AaronHForgeFlow commented
@AungKoKoLin1997 can you check pre-commit? maybe a rebase is enough...

2023-02-05 04:12 UTC, AungKoKoLin1997 commented
> can you check pre-commit? maybe a rebase is enough...

@AaronHForgeFlow Rebase can't be solved pre-commit issues at the moment. I will rebase again this PR after [that PR](https://github.com/OCA/account-analytic/pull/535) is already merged.

2023-02-11 17:20 UTC, AaronHForgeFlow commented
/ocabot merge nobump

2023-02-11 17:25 UTC, merged

2026-08-30 16:13 UTC, celm1990 commented
Hi, I think this module needs a migration script to convert the old project_id field to the new analytic_distribution field. Or is this handled in another way?

Thanks in advance.

2026-08-31 06:06 UTC, AungKoKoLin1997 commented
> Hi, I think this module needs a migration script to convert the old project_id field to the new analytic_distribution field.

@celm1990 You are right. I missed handling that when I worked on this PR.
I will follow up on this in the coming weeks. Please feel free to work on it if you need it urgently.