[16.0][mig] analytic_partner
OCA/account-analytic pull request #609
Opened 2023-11-18 17:48 UTC by dreispt

Supersedes https://github.com/OCA/account-analytic/pull/581

2024-03-20 09:01 UTC, chienandalu reviewed
HI @dreispt I'm struggling to find out why this module is still needed. Searching for previous internal issues the problem seemed to be that when the analytic account used had a partner set it took that one instead of the one in the move line...

But I can't reproduce that issue anymore. What case are we covering here right now? As far as I could test, the other partner is always the same as the partner.

2024-03-20 09:01 UTC, chienandalu commented on analytic_partner/readme/USAGE.rst
> +#. Go to **Invoicing > Configuration > Management > Analytic Items**.
```suggestion
#. Go to **Invoicing > Accounting > Management > Analytic Items**.
```

2024-03-20 09:01 UTC, chienandalu commented on analytic_partner/models/account_move_line.py
> +    def _prepare_analytic_lines(self):
I think that `_prepare_analytic_distribution_line` is the proper method to hook into now.

2024-06-24 09:30 UTC, maisim requested changes

2024-06-24 09:30 UTC, maisim commented on analytic_partner/models/account_move_line.py
> +    def _prepare_analytic_lines(self):
Hi @chienandalu , I think you are right, we can add `other_partner_id` to the dict returned by _prepare_analytic_distribution_line.
Somethings like:
```
def _prepare_analytic_distribution_line(self, distribution, account_id, distribution_on_each_plan):
    vals = super()._prepare_analytic_distribution_line(self, distribution, account_id, distribution_on_each_plan)
    vals['other_partner_id'] = self.move_id.partner_id.commercial_partner_id.id
    return vals
```
Hi @dreispt, How do you want to proceed? Can I create a PR on your fork?

2024-06-29 13:52 UTC, flotho commented
Hi @maisim , thanks for review with @chienandalu 
Ad @dreispt doesn't seems to have new commits since a long time, I think you could use his branch to create a new PR  to supersedes this one. Authoring will be kept anyway.
Regards

2024-08-22 08:44 UTC, dreispt commented
@maisim Yes, you are welcome to pull this branch into your fork and make your own PR.

2024-08-26 15:34 UTC, maisim commented
There is another PR (a third) to migrate this module to 16.0 : https://github.com/OCA/account-analytic/pull/672
It seems almost finish \o/

Can someone update the Migration to 16.0 issue https://github.com/OCA/account-analytic/issues/489 and close  the current PR https://github.com/OCA/account-analytic/pull/609  ?

2024-08-26 17:20 UTC, rafaelbn commented
/ocabot migration analytic_partner

2024-08-30 14:47 UTC, closed without merging