17.0 mig stock picking analytic
OCA/account-analytic pull request #628
Opened 2024-02-14 15:16 UTC by Wodran14

2024-03-13 20:57 UTC, astirpe requested changes

2024-03-13 20:57 UTC, astirpe commented on stock_picking_analytic/views/stock_picking.xml
> +                    readonly="state in ('done', 'cancel')"
This line should be removed:

```suggestion
```

2024-03-13 20:57 UTC, astirpe commented on stock_picking_analytic/views/stock_picking.xml
> +            </xpath>
This part gives error when installing the module. Should it be removed?

```suggestion
```

2024-03-18 12:05 UTC, dreispt commented
/ocabot migrate stock_picking_analytic

2024-03-18 12:05 UTC, dreispt commented
/ocabot migration stock_picking_analytic

2024-06-13 10:18 UTC, peluko00 commented
Any update @Wodran14 ?

2024-06-17 09:46 UTC, dcorio commented
It's just a warning, but I get:

`warnings.warn(f'Since Odoo 17, property {self}.states is no longer supported.')`

Does it have something to do with this?
```
analytic_distribution = fields.Json(
        inverse="_inverse_analytic_distribution",
        states={
            "done": [("readonly", True)],
            "cancel": [("readonly", True)],
        },
    )
```

2024-08-06 12:11 UTC, peluko00 commented
Hi @astirpe @dcorio, can you revise this in this another [pr](https://github.com/OCA/account-analytic/pull/676).
Thank you!

2024-08-22 09:02 UTC, dreispt commented
Superseded by #628

2024-08-22 09:02 UTC, closed without merging