[17.0][MIG] account_analytic_distribution_manual: Migration to 17.0
OCA/account-analytic pull request #700
Opened 2024-10-10 12:07 UTC by BernatObrador

2024-10-10 12:10 UTC, BernatObrador commented
Hi @carlos-lopez-tecnativa,

I'm working on migrating this module and have hit a roadblock with the component. It doesn't seem to be inheriting the properties correctly, and it's not recognizing the this.newTag and this.autoFill methods, which should be inherited.

Could you please help me figure out what's going wrong? I would really appreciate your assistance!

Thanks in advance!

2024-10-10 13:52 UTC, BernatObrador commented
@carlos-lopez-tecnativa, Ok nvm, I just found these methods are not in v17.

2024-10-18 07:46 UTC, BernatObrador commented
Hi @pedrobaeza!

I hope you're doing well! I’m facing some issues with the tests as they’re failing due to the tour, and I'm not sure how to resolve it. If you could lend a hand, I would really appreciate it!

Thank you in advance!

2024-10-18 18:54 UTC, pedrobaeza commented
Not sure. We had a similar problem some weeks ago that was solved with this: https://github.com/OCA/oca-ci/pull/78

@sbidoul @chienandalu do you have any clue?

2024-10-19 11:01 UTC, BernatObrador commented
Thanks, @pedrobaeza! If there's anything I can assist with, just let me know.

2024-11-07 08:24 UTC, chienandalu requested changes
You need to change the tour first

2024-11-07 08:24 UTC, chienandalu commented on account_analytic_distribution_manual/static/src/tests/tours/account_analytic_distribution_manual.esm.js
> +tour.register(
```suggestion
import { registry } from "@web/core/registry";
import { stepUtils } from "@web_tour/tour_service/tour_utils";

registry.category("web_tour.tours").add(
```

2024-11-07 08:24 UTC, chienandalu commented on account_analytic_distribution_manual/static/src/tests/tours/account_analytic_distribution_manual.esm.js
> +        ...tour.stepUtils.saveForm(),
```suggestion
        ...stepUtils.saveForm(),
```

2024-11-07 09:17 UTC, BernatObrador commented
Hi @chienandalu! Thank you very much for your contribution! The changes have been applied, but now the tour fails at the step "Create new invoice" with the trigger .o_list_button_add.

I'll take a closer look at this and see if I can resolve it. Thanks again for your help!

2024-11-07 09:19 UTC, chienandalu commented
Yes, now it's just a matter of debugging the steps :wink:

2024-12-11 12:20 UTC, BernatObrador commented
The tour tests are now working correctly. The issue lies with the tests themselves. I’m not sure why, but when running the tour directly through Odoo, everything works fine: analytic entries are generated as expected, and the other tests also pass without issues. However, when running Odoo tests that include the tour, it fails because it's not generating the analytic as intended. Do yo have any clue about why this can happen? Thanks in advance! @pedrobaeza @chienandalu

2024-12-11 12:22 UTC, pedrobaeza commented
Maybe @carlos-lopez-tecnativa can say.

2024-12-18 12:58 UTC, ppyczko approved these changes
LGTM, tested in runboat and code review 👍

2024-12-18 13:10 UTC, mpascuall approved these changes
LGTM, tested in runboat

2024-12-19 14:21 UTC, carlos-lopez-tecnativa requested changes
This is not working correctly. I found two issues, and I’ve attached a video for better explanation:

- Add a manual distribution.
- Remove the manual distribution.
- Add the manual distribution again. The analytic account is added, but the manual distribution is not applied. (first issue)
- Save the record, and a traceback is triggered(second issue).

![manual distribution](https://github.com/user-attachments/assets/4e874395-4af9-4edd-b4cb-edfda69461e6)

2024-12-19 14:21 UTC, carlos-lopez-tecnativa commented on account_analytic_distribution_manual/hooks.py
I think this hook can be removed. It was necessary during the transition from V15 to V16, but I believe it is no longer needed. What do you think @pedrobaeza

2024-12-19 14:55 UTC, pedrobaeza commented on account_analytic_distribution_manual/hooks.py
Correct. It was done for transforming the old information. If you are migrating from 15 to 17, and you need manual distributions, on the step from 15 to 16, you need to install the module to get data.

2024-12-19 19:01 UTC, BernatObrador commented
@carlos-lopez-tecnativa Thanks a lot for your time and valuable feedback! The bugs have been fixed. Could you please take another look and review the changes?

2024-12-23 20:06 UTC, carlos-lopez-tecnativa commented
> @carlos-lopez-tecnativa Thanks a lot for your time and valuable feedback! The bugs have been fixed. Could you please take another look and review the changes?

I tested again, but the issues are still present. Could you review it once more? I’m not sure if network latency on Runboat could be related.


https://github.com/user-attachments/assets/f87ef4d6-0759-41d8-bd8c-6f4d7b1897c0

2024-12-24 06:48 UTC, BernatObrador commented
[Grabación de pantalla desde 2024-12-24 07-43-43.webm](https://github.com/user-attachments/assets/c71b80b8-91f7-4a84-83d0-7b5c8631151b)
It's working fine when I try it on runboat. Could you please try on incognito tab? I guess there is maybe some cookies or cache there that can cause the problem!

2024-12-24 15:50 UTC, carlos-lopez-tecnativa requested changes

2024-12-24 15:50 UTC, carlos-lopez-tecnativa commented on account_analytic_distribution_manual/static/src/components/analytic_distribution/analytic_distribution.esm.js
> +                domain: [["company_id", "=", this.props.record.data.company_id[0]]],
I tested it locally, and without multicompany enabled, I got this error.

`Caused by: TypeError: Cannot read properties of undefined (reading '0')`

![image](https://github.com/user-attachments/assets/44b67598-2983-4996-9779-5fbe7762725a)

2024-12-27 07:38 UTC, BernatObrador commented
@carlos-lopez-tecnativa Can you review again? Thanks for your time!

2025-01-07 17:57 UTC, carlos-lopez-tecnativa reviewed
Tested and working fine. Please squash administrative commits(see https://github.com/OCA/maintainer-tools/wiki/Merge-commits-in-pull-requests). Thanks for the effort in the migration.

2025-01-08 07:12 UTC, BernatObrador commented
@carlos-lopez-tecnativa Done!

2025-01-08 11:41 UTC, carlos-lopez-tecnativa requested changes
Could you review this use case? It’s not working as expected

2025-01-08 11:41 UTC, carlos-lopez-tecnativa commented on account_analytic_distribution_manual/static/src/components/analytic_distribution/analytic_distribution.esm.js
> +        }
- Create an invoice, add a manual distribution, and save.
- Edit the invoice and remove the manual distribution.
- Focus on another element.
- Discard the changes.

Issue: The manual distribution is not displayed; it’s lost after discarding the changes


V17

https://github.com/user-attachments/assets/d8b8d7bc-4897-4bed-bea0-60d134ef34f5

V16

https://github.com/user-attachments/assets/e221b6fa-13b4-4ae0-8a6a-ce042817ea85

2025-01-15 12:43 UTC, BernatObrador commented on account_analytic_distribution_manual/static/src/components/analytic_distribution/analytic_distribution.esm.js
> +        }
The issue lies in the fact that the method willUpdate(nextProps) has been replaced with willUpdateRecord(record).

The challenge is that I can no longer determine whether force_refresh_discart should be applied, as this.props no longer includes this.props.record.data.id. This makes it impossible to track whether the user is discarding changes.

Do you have any suggestions on how to resolve this? I specifically need a reliable way to detect when the user discards changes so that I can apply the correct distribution.

2025-02-07 17:19 UTC, carlos-lopez-tecnativa commented on account_analytic_distribution_manual/static/src/components/analytic_distribution/analytic_distribution.esm.js
> +        }
Hi @BernatObrador sorry for the delay
I debugged a bit in the browser—please try this:
Inherit the function `willUpdateRecord`, as you mentioned, since it is now the replacement for `willUpdate`.

When the user is editing, `record.dirty = True`, but when they save or discard, `record.dirty = False`. I think this flag can be used to recover the old value from `record.data.manual_distribution_id` or from `this.props.record.data.manual_distribution_id`, depending on which variable is more up to date.

I hope this helps! If you have any questions, please let me know. Thanks!

![image](https://github.com/user-attachments/assets/f496c3f5-6ffb-44d9-9e24-d605506d22e8)

2025-02-07 17:22 UTC, carlos-lopez-tecnativa commented on account_analytic_distribution_manual/static/src/components/analytic_distribution/analytic_distribution.esm.js
> +        }
Another tip:
When the user discards, if you inspect the `Call Stack`, it might come from `_discard()`. At some point, you might be able to intercept this. I'm not sure, just thinking out loud.

![image](https://github.com/user-attachments/assets/46a28572-6bb1-4433-bf86-014abf1ea938)

2025-02-14 11:29 UTC, BernatObrador commented on account_analytic_distribution_manual/static/src/components/analytic_distribution/analytic_distribution.esm.js
> +        }
Hi @carlos-lopez-tecnativa, thanks a lot for your time! What you found looks perfect.

I just tested it with record.dirty, and it seems to be working well. Could you please review it again?

If the distribution has changed and it's not dirty (which means it has been saved or discarded), we always need to refresh the distribution!

2025-02-19 19:27 UTC, carlos-lopez-tecnativa approved these changes
LGTM, thanks for the effort!

2025-02-19 19:30 UTC, pedrobaeza commented
/ocabot migration account_analytic_distribution_manual
/ocabot merge nobump

2025-02-21 07:10 UTC, BernatObrador commented
@pedrobaeza Something went wrong when the bot was merging. Could you please try again? Thanks!

2025-02-21 07:12 UTC, pedrobaeza commented
/ocabot merge nobump

2025-02-21 07:22 UTC, merged