[ADD] account_analytic_distribution_manual_date: New module account_a…
OCA/account-analytic pull request #702
Opened 2024-10-14 14:26 UTC by BernatObrador

…nalytic_distribution_manual_date

2024-12-10 09:31 UTC, peluko00 approved these changes
LGTM, tested in runboat

2024-12-10 11:47 UTC, mpascuall approved these changes
LGTM, tested in runboat

2025-02-27 09:37 UTC, BernatObrador commented
@carlos-lopez-tecnativa Could you review please? Thanks!

2025-02-27 12:15 UTC, carlos-lopez-tecnativa requested changes
Code review

2025-02-27 12:15 UTC, carlos-lopez-tecnativa commented on account_analytic_distribution_manual_date/readme/USAGE.md
> +   - Now, the available Manual Distributions will be filtered based on the **Invoice Date** or **Today's Date**.
I think some points are redundant; both the main point and the secondary details try to say the same thing. For example:

> 3. **Create an Invoice or Vendor Bill**:
> 
>    -  Proceed to create a new **Invoice** or **Vendor Bill**.

2025-02-27 12:15 UTC, carlos-lopez-tecnativa commented on account_analytic_distribution_manual_date/models/account_move.py
> +        return super().write(vals)
Please remove the blank lines.

2025-02-27 12:15 UTC, carlos-lopez-tecnativa commented on account_analytic_distribution_manual_date/models/account_move.py
> +                self._check_manual_distribution_date(manual_distribution, date)
Why keep two functions that serve the same purpose? Can this be simplified?

2025-02-27 12:15 UTC, carlos-lopez-tecnativa commented on account_analytic_distribution_manual_date/models/account_move.py
> +        if manual_distribution:
This `if` can be removed since the function is only called when `manual_distribution` is set.

2025-02-27 12:15 UTC, carlos-lopez-tecnativa commented on account_analytic_distribution_manual_date/tests/test_manual_distribution_date.py
> +                ],
Could you use the [Command](https://github.com/odoo/odoo/blob/370de95190cf07f17281f0ed6365b6806663cac2/odoo/fields.py#L4227-L4256) class? It is more readable.
```suggestion
                "invoice_line_ids": [
                   Command.create(
                        {
                            "name": "Product A",
                            "quantity": 1,
                            "price_unit": 100.0,
                            "manual_distribution_id": cls.manual_distribution.id,
                        },
                    )
                ],
```

2025-02-27 12:15 UTC, carlos-lopez-tecnativa commented on account_analytic_distribution_manual_date/tests/test_manual_distribution_date.py
> +                    )
The same here, and check the remaining code, please.

```suggestion
                    Command.update(
                        self.invoice.invoice_line_ids[0].id,
                        {
                            "manual_distribution_id": self.manual_distribution.id,
                        },
                    )
```

2025-02-27 12:15 UTC, carlos-lopez-tecnativa commented on account_analytic_distribution_manual_date/views/account_analytic_distribution_manual_views.xml
> +                    <field name="end_date" string="End Date" widget="date" />
I think the widget is unnecessary and can be removed. According to the field type, Odoo uses the widget automatically. Why assign an explicit widget if it has the same effect?

2025-04-04 12:56 UTC, BernatObrador commented
@carlos-lopez-tecnativa Thanks a lot for your feedback! Just done the changes. Could you review again please?

2025-04-07 18:41 UTC, carlos-lopez-tecnativa requested changes
Just a minor change

2025-04-07 18:41 UTC, carlos-lopez-tecnativa commented on account_analytic_distribution_manual_date/models/account_analytic_distribution_manual.py
> +    end_date = fields.Date()
Could you add a constraint to prevent errors in dates where date_end is earlier than date_start?

![image](https://github.com/user-attachments/assets/055ac317-2a9e-49d5-80b6-b062b97335db)

2025-04-14 14:31 UTC, carlos-lopez-tecnativa approved these changes
LGTM

@pedrobaeza could you please review this?

2025-04-14 15:10 UTC, pedrobaeza commented
Weird use case for this, but OK being a new module on top:

/ocabot merge nobump

2025-04-14 15:18 UTC, merged