[17.0][mig] purchase_analytic
OCA/account-analytic pull request #707
Opened 2024-10-24 14:32 UTC by aisopuro

Replaces (resurrects?) #626

2024-10-24 14:39 UTC, aisopuro commented
Trying to re-open this, since the original PR was closed due to inactivity. I only did some pre-commit fixes and squashed them into @Wodran14 's original pre-commit commit.

2024-10-24 14:41 UTC, aisopuro commented
The coverage appears to be failing due to there not being tests for "empty cases", e.g. computing the value correctly if there are no lines on an order.

Could the maintainers give an opinion, is it required to meet those code coverage goals on a migration PR?

2024-12-16 22:18 UTC, StefanRijnhart commented
/ocabot migration purchase_analytic

2025-01-03 18:44 UTC, CLaurelB commented
Hello,

Functional test: LGTM 👍 

Regarding the coverage: IMHO, there could be a test to remove the analytic distribution on the PO and then assert that the analytic distributions of the lines, previously set, remain intact. Additionally, there could be a test to set the same analytic distribution on multiple lines and verify that the analytic distribution of the PO is correctly set.

Best regards.

2025-01-06 23:05 UTC, CLaurelB commented
Hello @aisopuro,

Maybe this could help: https://github.com/avoinsystems/account-analytic/pull/2

Best regards.

2025-01-16 10:52 UTC, aisopuro commented
OK, thank you @CLaurelB for the coverage expansion, that commit is now included here. All checks are green so this seems ready to review by maintainers.

2025-01-16 18:40 UTC, luisg123v requested changes

2025-01-16 18:40 UTC, luisg123v commented on purchase_analytic/views/purchase_views.xml
> +<?xml version="1.0" ?>
Why this? I'd avoid this, AFAIK it's preferred to provide the encoding explicitly.

2025-01-16 18:40 UTC, luisg123v commented on purchase_analytic/i18n/purchase_analytic.pot
> +# Translation of Odoo Server.
There are missing commits present in 16.0, mainly related to translations, e.g. de8e27fa84267343190adc2874042efe9593cddf. I'd suggest retrieving the history again and then cherrypicking the migration commits.

2025-01-16 18:40 UTC, luisg123v commented on purchase_analytic/models/purchase.py
> +        When set analytic_distribution set analytic distribution on all order lines
"when set**ting**

Same in the below docstring.

2025-01-16 18:40 UTC, luisg123v commented on purchase_analytic/tests/test_purchase_analytic.py
> +                    "product_uom": self.uom_id.id,
I'd suggest making these params configurable and provide default values, so it may be called without params but also being able to provide some of them.

2025-01-16 18:40 UTC, luisg123v commented on purchase_analytic/tests/test_purchase_analytic.py
> +            Command.create(
Why don't you pass the order as param instead?

2025-01-16 18:40 UTC, luisg123v commented on purchase_analytic/tests/test_purchase_analytic.py
> +        analytic_plan = self.env["account.analytic.plan"].create({"name": "Plan Test"})
Why this? Could you document it in commit description?

2025-01-16 18:40 UTC, luisg123v commented on purchase_analytic/README.rst
> +-  Laetitia Gangloff <laetitia.gangloff@acsone.eu>
Isn't fixing double spaces part of the changes performed by precommit?

I mean:

```suggestion
- Laetitia Gangloff <laetitia.gangloff@acsone.eu>
```

2025-01-17 15:19 UTC, aisopuro commented
Heads up, I may not have time anytime soon to fix the issues brought up by the review. So if someone wants to push this through, feel free to re-steal the PR from me.

2025-01-21 09:13 UTC, StefanRijnhart commented
Closing in favour of https://github.com/OCA/account-analytic/pull/731. Thank you for your work!

2025-01-21 09:13 UTC, closed without merging