[18.0][MIG] stock_analytic: Migration to 18.0
OCA/account-analytic pull request #710
Opened 2024-11-20 09:47 UTC by peluko00

2024-11-20 12:26 UTC, ppyczko approved these changes
LGTM!

2024-11-22 09:39 UTC, mpascuall approved these changes
LGTM, tested in runboat

2024-11-26 16:43 UTC, houssine78 commented
@pedrobaeza this PR can be merged. thanks !

2024-12-01 17:31 UTC, dreispt approved these changes

2024-12-01 17:32 UTC, dreispt commented
/ocabot migration stock_analytic
/ocabot merge nobump

2025-01-10 14:04 UTC, gbrito commented
@dreispt is there anything we can do to merge this?

2025-01-10 14:32 UTC, gbrito requested changes
@peluko00 Can you please push this changes?

2025-01-10 14:32 UTC, gbrito commented on stock_analytic/tests/test_stock_picking.py
> +                "company_ids": [(4, [cls.env.ref("base.main_company").id])],
can you update this so the test pass and it can be merge
```suggestion
                "company_ids": [Command.link(cls.env.ref("base.main_company").id)],
```

2025-01-10 14:32 UTC, gbrito commented on stock_analytic/tests/test_stock_picking.py
> +                "company_ids": [(4, [cls.env.ref("base.main_company").id])],
can you update this so the test pass and it can be merge
```suggestion
                "company_ids": [Command.link(cls.env.ref("base.main_company").id)],
```

2025-01-10 14:32 UTC, gbrito commented on stock_analytic/tests/test_stock_picking.py
> +                "company_ids": [(4, [cls.env.ref("base.main_company").id])],
can you update this so the test pass and it can be merge
```suggestion
                "company_ids": [Command.link(cls.env.ref("base.main_company").id)],
```

2025-01-13 08:41 UTC, peluko00 commented
> @dreispt is there anything we can do to merge this?

Done, thanks!

2025-01-13 08:57 UTC, gbrito approved these changes

2025-01-13 09:00 UTC, gbrito commented
@peluko00 thanks, good work

2025-01-24 13:01 UTC, gbrito commented
@dreispt can you press the button?

2025-01-24 17:44 UTC, dreispt commented
/ocabot merge nobump

2025-01-24 17:50 UTC, merged