[18.0][FIX] account_analytic_tag: Add analytic tags to taxes with analytic
OCA/account-analytic pull request #724
Opened 2024-12-10 08:27 UTC by pedrobaeza

Forward-port of #722 and #723

If you mark explicitly a tax with analytic, or have repartition lines without account, then the analytic tags should be propagated to these lines.

@Tecnativa TT52120

2024-12-10 09:02 UTC, carlosdauden approved these changes

2024-12-10 09:03 UTC, carlosdauden commented
Test failed is related?

2024-12-10 09:04 UTC, carlosdauden requested changes
Test failed

2024-12-10 09:05 UTC, pedrobaeza commented
In local it's working:

![imagen](https://github.com/user-attachments/assets/872d5b10-6d81-4247-9f76-b12049e53223)

I have to check what's going on.

2026-01-07 13:15 UTC, victoralmau approved these changes

2026-05-11 08:27 UTC, carlosdauden commented
Retry run tests

2026-07-02 08:36 UTC, eduezerouali-tecnativa commented
@pedrobaeza Approach has to change as  `_compute_all_tax` is no longer in 18. Would you like me to take over it?

2026-07-02 08:46 UTC, pedrobaeza commented
OK, go ahead.

2026-07-02 10:56 UTC, eduezerouali-tecnativa commented
Changed to `_prepare_base_line_tax_repartition_grouping_key` and `_prepare_tax_line_repartition_grouping_key`.
ping @pedrobaeza @victoralmau @carlosdauden could you review please?

2026-07-02 11:18 UTC, pedrobaeza commented
Thanks, working according to the test and code review!

/ocabot merge patch

Please fw-port it 19

2026-07-02 11:30 UTC, merged