[ADD][9.0] account_analytic_distribution module
OCA/account-analytic pull request #90
Opened 2017-04-26 17:37 UTC by cubells

New module to use as alternative to old account_analytic_plans module.

- Add spanish po file
- Add tests

cc @Tecnativa

2017-04-26 18:43 UTC, pedrobaeza requested changes

2017-04-26 18:43 UTC, pedrobaeza commented on account_analytic_distribution/README.rst
> +This module is a simpler alternative to official 'account_analytic_plans'
Change this text, as now in version 9.0, there's no account_analytic_plans module, and also explains the purpose (as if you don't know account_analytic_plans).

2017-04-26 18:43 UTC, pedrobaeza commented on account_analytic_distribution/README.rst
> +Invoicing > Configuration > Analytic Accounting > Analytic Distributions
Put a little more in this topic, specifying what fields you have to fill, and using `#. ` elements.

2017-04-26 18:43 UTC, pedrobaeza commented on account_analytic_distribution/README.rst
> +For further information, please visit:
Remove this part

2017-04-26 18:43 UTC, pedrobaeza commented on account_analytic_distribution/README.rst
> +TODO: Add 'Analytic Distribution' field to invoices and other account objects
Add this as a bullet point

2017-04-26 18:43 UTC, pedrobaeza commented on account_analytic_distribution/README.rst
> +There will be developed other addons (like 'sale_analytic_distribution' or
Add this as a bullet point

2017-04-26 18:43 UTC, pedrobaeza commented on account_analytic_distribution/models/__init__.py
> +# flake8: noqa
Remove this line as this a hack for not checking flake8, and fix possible errors.

2017-04-26 18:43 UTC, pedrobaeza commented on account_analytic_distribution/models/account_analytic_distribution.py
> +            _('Distribution name must be unique per Company!')),
Fix indentation

2017-04-26 18:43 UTC, pedrobaeza commented on account_analytic_distribution/models/account_analytic_distribution.py
> +    def get_default_company(self):
Why 2 methods for the same? I supposed that this is due to old API not letting to overwrite, but not you can make only one

2017-04-26 18:43 UTC, pedrobaeza commented on account_analytic_distribution/models/account_analytic_distribution_rule.py
> +class AccountAnalyticDistributionRule(models.Model):
This should go in the same file as the account.analytic.distribution, as it's a one2many model (like sale.order.line).

2017-04-26 18:43 UTC, pedrobaeza commented on account_analytic_distribution/README.rst
> +TODO: Add 'Analytic Distribution' field to invoices and other account objects
Is this still TODO? I see the distribution in the invoice line...

2017-04-26 18:43 UTC, pedrobaeza commented on account_analytic_distribution/tests/test_analytic_distribution.py
> +        cls.account1 = cls.env.ref('analytic.analytic_agrolait')
Don't use demo data, but create yours

2017-05-08 11:59 UTC, pedrobaeza commented
@cubells please implement the policy per company as discussed.

2017-05-08 14:44 UTC, cubells commented
@pedrobaeza done.

2017-05-09 07:25 UTC, pedrobaeza approved these changes

2017-05-09 07:26 UTC, pedrobaeza commented
@chienandalu @luismontalba please review

2017-05-09 07:50 UTC, fclementic2c commented
@cubells @pedrobaeza I wanted to test this tool on runbot but I can't make it works :\ 
look at the invoice : INV/2017/0005, I do not get 2 analytic lines per invoice line as expected....maybe I did something wrong.

2017-05-09 08:25 UTC, cubells commented
@fclementic2c 
I'll test this problem...

2017-05-09 09:10 UTC, cubells commented
@fclementic2c 
The problem was that in runbot module account_analytic_no_lines was installed.

As stated in its README file:

> This module hides analytics lines from accounting menus and disable their generation from an invoice or a move line.

Can you retest this module with account_analytic_no_lines not installed?

2017-05-09 11:17 UTC, luismontalba approved these changes
Functionality tested on runbot

2017-05-09 11:38 UTC, fclementic2c commented
@cubells 
Its works better thanks :)

I just have one little concern about ergonomy: why not adding a constraint on so/po/invoices lines: if you select a distribution then block the analytic account field (since this info will be overwritten anyway on analytic lines)

Otherwise, it is ok for me
Thanks for your module

+1:

2017-05-30 15:25 UTC, merged