[ADD][9.0] purchase_analytic_distribution module
OCA/account-analytic pull request #93
Opened 2017-04-27 18:47 UTC by cubells

New module to use as alternative to old purchase_analytic_plans module.

- Update README
- Update views
- Update file structure

WIP cause this module depends on #90

cc @Tecnativa

2017-06-08 11:40 UTC, pedrobaeza requested changes

2017-06-08 11:40 UTC, pedrobaeza commented on purchase_analytic_distribution/i18n/purchase_analytic_plans.pot
> +# Translation of Odoo Server.
Remove this file

2017-06-08 11:40 UTC, pedrobaeza commented on purchase_analytic_distribution/README.rst
> +* Vicent Cubells <antonio.espinosa@tecnativa.com>
Put correctly your address

2017-06-08 11:40 UTC, pedrobaeza commented on purchase_analytic_distribution/__openerp__.py
> +    "author": "Odoo SA, "
Are you sure Odoo puts their authorship this way? Check default value of author key in code, which is the one they use.

2017-06-08 11:40 UTC, pedrobaeza commented on purchase_analytic_distribution/models/purchase.py
> +        string='Analytic Distribution',
Put `oldname='analytics_id'` for automatic migration.

2017-06-08 11:40 UTC, pedrobaeza commented on purchase_analytic_distribution/views/purchase_view.xml
> +                <attribute name="editable"/>
Why removing the editable attribute? You can put the analytic distribution in the tree itself.

2017-06-08 23:40 UTC, pedrobaeza approved these changes

2017-06-08 23:44 UTC, pedrobaeza commented
@luismontalba please review this one

2017-06-09 08:12 UTC, luismontalba commented on purchase_analytic_distribution/README.rst
> +
Purchase order instead off sale order?

2017-06-09 08:18 UTC, luismontalba commented
Analytic entries are not created when confirming invoice from a purchase order with analytic distribution in order lines, is it related to this module as the readme explains?

2017-06-09 08:19 UTC, pedrobaeza commented
This module only passes the analytic distribution from the purchase order to the invoice.

2017-06-09 08:31 UTC, luismontalba approved these changes
Functionality tested on runbot

2017-06-09 09:49 UTC, merged